[api]
config_binlog = "http://xxxxxx:8000/api/v1/cluster/conf_cluster_binlog"
config_pump = "http://xxxxxx:8000/api/v1/cluster/conf_cluster_pump"
config_drainer = "http://xxxxxx:8000/api/v1/cluster/conf_cluster_drainer"
config_restart = "http://xxxxxx:8000/api/v1/cluster/conf_cluster_restart"
[cmdb]
appkey = "com.xxx.xxx.xxx.resource"
username = "abc"
password = "123"
cmdb_port = 5002
cmdb_host = "1.1.1.1,2.2.2.2,3.3.3.3"
cmdb_db = "backupnetes"
[task]
path = "/opt/"
default-gc = "168h"
[blade]
bladeappkey = "test.test"
bladeuser = "admin"
bladeport = 4000